import * as core from '@actions/core';
import { ArchitectureContext, ArchitecturePayload } from './types';
import { createAnthropicClient } from './anthropicClient';
import { buildArchitecturePrompt } from './architecturePrompt.template';
import { extractJson } from './extractJson';

const FALLBACK_MERMAID =
  'graph TD\n' +
  '  classDef clean fill:#d4edda,stroke:#28a745,color:#155724;\n' +
  '  Codebase\n' +
  '  class Codebase clean;';

/** Strips any ```mermaid fences Claude may have left inside the JSON string. */
function stripMermaidFence(s: string): string {
  const fenced = s.match(/```(?:mermaid)?\s*([\s\S]*?)```/);
  return (fenced ? fenced[1] : s).trim();
}

function parseArchitecture(raw: string): { mermaid: string; summary: string } {
  try {
    const obj = JSON.parse(extractJson(raw)) as { mermaid?: unknown; summary?: unknown };
    if (obj && typeof obj.mermaid === 'string' && obj.mermaid.trim()) {
      return {
        mermaid: stripMermaidFence(obj.mermaid),
        summary: typeof obj.summary === 'string' ? obj.summary.trim() : ''
      };
    }
  } catch {
    // Fall through to fenced-block / fallback handling below.
  }

  const fence = raw.match(/```mermaid\s*([\s\S]*?)```/);
  if (fence) return { mermaid: fence[1].trim(), summary: '' };

  core.warning('PatternBuddy: Could not parse an architecture diagram from Claude. Using fallback.');
  return { mermaid: FALLBACK_MERMAID, summary: '' };
}

function renderArchitectureDoc(context: ArchitectureContext, mermaid: string, summary: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const notes = summary || '_No notes generated for this update._';

  return `# 🗺️ Architecture Map

> **Auto-generated by [PatternBuddy](../.pattern-pointers.md).** Regenerated from the
> accumulated pattern memory after every merged PR — **do not edit by hand**, your
> changes will be overwritten on the next merge.
>
> Last updated: **PR #${context.prNumber} — ${context.prTitle}** · ${date}

\`\`\`mermaid
${mermaid}
\`\`\`

### Legend

- 🟢 **Clean** — sound patterns (Factory, Repository, SOLID-compliant, loose coupling)
- 🟡 **Watch** — tight coupling or emerging anti-patterns worth keeping an eye on
- 🔴 **Danger** — God classes, circular dependencies, high coupling centrality

### Architect's notes

${notes}
`;
}

export async function generateArchitectureMap(context: ArchitectureContext): Promise<ArchitectureContext> {
  const client = createAnthropicClient();
  const prompt = buildArchitecturePrompt(context);

  const message = await client.messages.create({
    model:      'claude-sonnet-4-6',
    max_tokens: 4096,
    messages: [{ role: 'user', content: prompt }]
  });

  const block = message.content[0];
  if (block.type !== 'text') {
    throw new Error('Unexpected Claude response type — expected text block.');
  }

  const { mermaid, summary } = parseArchitecture(block.text);
  const markdown = renderArchitectureDoc(context, mermaid, summary);

  const architecture: ArchitecturePayload = { mermaid, summary, markdown };
  return { ...context, architecture };
}
